
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace DynThings.Data.Models
{

using System;
    using System.Collections.Generic;
    
public partial class APIUtilisation
{

    public long ID { get; set; }

    public Nullable<long> AppID { get; set; }

    public Nullable<System.Guid> Token { get; set; }

    public int StatusID { get; set; }

    public long MethodID { get; set; }

    public System.DateTime TimeStampUTC { get; set; }

    public string Notes { get; set; }



    public virtual APIMethod APIMethod { get; set; }

}

}
