
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace DynThings.Data.Models
{

using System;
    using System.Collections.Generic;
    
public partial class App
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public App()
    {

        this.AppAPIEntitys = new HashSet<AppAPIEntity>();

        this.AppEndpointTypes = new HashSet<AppEndpointType>();

        this.AppMediaFiles = new HashSet<AppMediaFile>();

        this.AppThingCategorys = new HashSet<AppThingCategory>();

        this.AppThingExtensions = new HashSet<AppThingExtension>();

        this.AppUserTokens = new HashSet<AppUserToken>();

    }


    public long ID { get; set; }

    public System.Guid GUID { get; set; }

    public System.Guid Key { get; set; }

    public string Title { get; set; }

    public string Description { get; set; }

    public string CreatedByID { get; set; }

    public System.DateTime CreateDate { get; set; }

    public int StatusID { get; set; }

    public bool IsStoreApp { get; set; }

    public string DevelopedByName { get; set; }

    public Nullable<System.DateTime> StoreAppLastUpdate { get; set; }

    public double Version { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<AppAPIEntity> AppAPIEntitys { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<AppEndpointType> AppEndpointTypes { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<AppMediaFile> AppMediaFiles { get; set; }

    public virtual AppStatuss AppStatuss { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<AppThingCategory> AppThingCategorys { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<AppThingExtension> AppThingExtensions { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<AppUserToken> AppUserTokens { get; set; }

}

}
