
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace DynThings.Data.Models
{

using System;
    using System.Collections.Generic;
    
public partial class AppAPIEntity
{

    public long ID { get; set; }

    public long AppID { get; set; }

    public long SystemEntityID { get; set; }



    public virtual App App { get; set; }

    public virtual SystemEntity SystemEntity { get; set; }

}

}
