
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace DynThings.Data.Models
{

using System;
    using System.Collections.Generic;
    
public partial class AppEndpointType
{

    public long ID { get; set; }

    public string Code { get; set; }

    public System.Guid GUID { get; set; }

    public long AppID { get; set; }

    public string Title { get; set; }

    public string Measurement { get; set; }

    public long TypeCategoryID { get; set; }

    public System.Guid IconGUID { get; set; }



    public virtual EndPointTypeCategory EndPointTypeCategory { get; set; }

    public virtual App App { get; set; }

}

}
