
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace DynThings.Data.Models
{

using System;
    using System.Collections.Generic;
    
public partial class AppUserToken
{

    public long ID { get; set; }

    public Nullable<long> AppID { get; set; }

    public string AspNetUserID { get; set; }

    public Nullable<System.Guid> Token { get; set; }

    public Nullable<System.DateTime> ExpireDate { get; set; }

    public Nullable<System.DateTime> CreateDate { get; set; }



    public virtual AspNetUser AspNetUser { get; set; }

    public virtual App App { get; set; }

}

}
