//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DynThings.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Command
    {
        public long ID { get; set; }
        public Nullable<long> DeviceID { get; set; }
        public string Description { get; set; }
        public string Command1 { get; set; }
        public string OwnerID { get; set; }
    
        public virtual Device Device { get; set; }
    }
}
