
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace DynThings.Data.Models
{

using System;
    using System.Collections.Generic;
    
public partial class DBChanx
{

    public long ID { get; set; }

    public long CentralChangeID { get; set; }

    public string ChangeCode { get; set; }

    public System.DateTime TimeStamp { get; set; }

}

}
