
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace DynThings.Data.Models
{

using System;
    using System.Collections.Generic;
    
public partial class DeviceIO
{

    public long ID { get; set; }

    public Nullable<long> DeviceID { get; set; }

    public Nullable<long> IOTypeID { get; set; }

    public string Valu { get; set; }

    public Nullable<System.DateTime> TimeStamp { get; set; }

    public Nullable<System.DateTime> ExecTimeStamp { get; set; }

    public Nullable<System.DateTime> ScheduleTimeStamp { get; set; }

    public Nullable<System.DateTime> TimeStamp_UTC { get; set; }

    public Nullable<System.DateTime> ExecTimeStamp_UTC { get; set; }

    public Nullable<System.DateTime> ScheduleTimeStamp_UTC { get; set; }



    public virtual Device Device { get; set; }

    public virtual IOType IOType { get; set; }

    public virtual IOType IOType1 { get; set; }

}

}
