
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace DynThings.Data.Models
{

using System;
    using System.Collections.Generic;
    
public partial class DynSetting
{

    public long ID { get; set; }

    public float DBVersion { get; set; }

    public bool DevelopmentMode { get; set; }

    public int DefaultRecordsPerMaster { get; set; }

    public int DefaultRecordsPerChild { get; set; }

    public System.Guid PlatformKey { get; set; }

    public bool PublicAccess { get; set; }

    public bool PublicSignUP { get; set; }

    public bool EnableSystemLogger { get; set; }

    public int App_TimeZone { get; set; }

    public string PlatformTitle { get; set; }

    public System.DateTime LastCentralSync { get; set; }

    public System.DateTime DeploymentTimeStamp { get; set; }

}

}
