
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace DynThings.Data.Models
{

using System;
    using System.Collections.Generic;
    
public partial class EndPointIO
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public EndPointIO()
    {

        this.ThingEnds = new HashSet<ThingEnd>();

    }


    public long ID { get; set; }

    public long EndPointID { get; set; }

    public long IOTypeID { get; set; }

    public long EndPointTypeID { get; set; }

    public string Valu { get; set; }

    public System.DateTime TimeStamp { get; set; }

    public Nullable<System.DateTime> ExecTimeStamp { get; set; }

    public Nullable<System.DateTime> ScheduleTimeStamp { get; set; }

    public Nullable<System.DateTime> TimeStamp_UTC { get; set; }

    public Nullable<System.DateTime> ExecTimeStamp_UTC { get; set; }

    public Nullable<System.DateTime> ScheduleTimeStamp_UTC { get; set; }

    public long ThingID { get; set; }



    public virtual EndPointType EndPointType { get; set; }

    public virtual Endpoint Endpoint { get; set; }

    public virtual IOType IOType { get; set; }

    public virtual Thing Thing { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<ThingEnd> ThingEnds { get; set; }

}

}
