//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DynThings.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EndPointTrigger
    {
        public long ID { get; set; }
        public string Title { get; set; }
        public Nullable<long> TriggerEndPointID { get; set; }
        public Nullable<long> ActionEndPointID { get; set; }
        public Nullable<long> CommandID { get; set; }
    }
}
