//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DynThings.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LinkEndpointsLocation
    {
        public long ID { get; set; }
        public Nullable<long> LocationID { get; set; }
        public Nullable<long> EndpointID { get; set; }
    
        public virtual Location Location { get; set; }
        public virtual Endpoint Endpoint { get; set; }
    }
}
