
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace DynThings.Data.Models
{

using System;
    using System.Collections.Generic;
    
public partial class LinkThingsLocation
{

    public long ID { get; set; }

    public Nullable<long> LocationID { get; set; }

    public Nullable<long> ThingID { get; set; }

    public string CreateByUser { get; set; }

    public Nullable<System.DateTime> CreateTimeStamp { get; set; }



    public virtual Location Location { get; set; }

    public virtual Location Location1 { get; set; }

    public virtual Thing Thing { get; set; }

}

}
