
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace DynThings.Data.Models
{

using System;
    using System.Collections.Generic;
    
public partial class ThingExtenstionValue
{

    public long ID { get; set; }

    public long ThingExtenstionID { get; set; }

    public Nullable<long> ThingID { get; set; }

    public string Valu { get; set; }



    public virtual ThingExtenstion ThingExtenstion { get; set; }

    public virtual Thing Thing { get; set; }

}

}
