
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace DynThings.Data.Models
{

using System;
    using System.Collections.Generic;
    
public partial class Thing
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Thing()
    {

        this.AlertConditions = new HashSet<AlertCondition>();

        this.EndPointIOs = new HashSet<EndPointIO>();

        this.Endpoints = new HashSet<Endpoint>();

        this.LinkThingsLocations = new HashSet<LinkThingsLocation>();

        this.ThingEnds = new HashSet<ThingEnd>();

        this.ThingExtenstionValues = new HashSet<ThingExtenstionValue>();

    }


    public long ID { get; set; }

    public string Title { get; set; }

    public long CategoryID { get; set; }

    public string CreateByUser { get; set; }

    public Nullable<System.DateTime> CreateTimeStamp { get; set; }

    public int UTC_Diff { get; set; }

    public int ObjectStatusID { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<AlertCondition> AlertConditions { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<EndPointIO> EndPointIOs { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Endpoint> Endpoints { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<LinkThingsLocation> LinkThingsLocations { get; set; }

    public virtual ThingCategory ThingCategory { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<ThingEnd> ThingEnds { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<ThingExtenstionValue> ThingExtenstionValues { get; set; }

}

}
