
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace DynThings.Data.Models
{

using System;
    using System.Collections.Generic;
    
public partial class ThingEnd
{

    public long ID { get; set; }

    public Nullable<long> ThingID { get; set; }

    public Nullable<long> EndPointTypeID { get; set; }

    public string LastIOValue { get; set; }

    public Nullable<long> LastIOID { get; set; }

    public Nullable<System.DateTime> LastIOTimeStamp { get; set; }

    public Nullable<System.DateTime> LastIOTimeStampUTC { get; set; }



    public virtual EndPointIO EndPointIO { get; set; }

    public virtual EndPointType EndPointType { get; set; }

    public virtual Thing Thing { get; set; }

}

}
