
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace DynThings.Data.Models
{

using System;
    using System.Collections.Generic;
    
public partial class ThingCategory
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public ThingCategory()
    {

        this.ThingExtenstions = new HashSet<ThingExtenstion>();

        this.Things = new HashSet<Thing>();

    }


    public long ID { get; set; }

    public string Title { get; set; }

    public Nullable<long> IconID { get; set; }

    public Nullable<System.Guid> GUID { get; set; }



    public virtual MediaFile MediaFile { get; set; }

    public virtual MediaFile MediaFile1 { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<ThingExtenstion> ThingExtenstions { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Thing> Things { get; set; }

}

}
