
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace DynThings.Data.Models
{

using System;
    using System.Collections.Generic;
    
public partial class UserNotification
{

    public long ID { get; set; }

    public string UserID { get; set; }

    public Nullable<long> IsRead { get; set; }

    public string Txt { get; set; }

    public Nullable<long> NotificationTypeID { get; set; }

    public Nullable<long> RefID { get; set; }

    public Nullable<System.DateTime> AlertTimeStamp { get; set; }

    public Nullable<bool> IsEmailSent { get; set; }



    public virtual AspNetUser AspNetUser { get; set; }

}

}
