//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DynThings.WebPortal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Location
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Location()
        {
            this.LinkLocationsLocationViews = new HashSet<LinkLocationsLocationView>();
            this.LinkEndpointsLocations = new HashSet<LinkEndpointsLocation>();
        }
    
        public long ID { get; set; }
        public System.Guid GUID { get; set; }
        public string Title { get; set; }
        public string LongitudeY { get; set; }
        public string LatitudeX { get; set; }
        public bool isActive { get; set; }
        public long Status { get; set; }
        public long IconID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LinkLocationsLocationView> LinkLocationsLocationViews { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LinkEndpointsLocation> LinkEndpointsLocations { get; set; }
    }
}
