//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DynThings.DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class EndPointIO
    {
        public long ID { get; set; }
        public long EndPointID { get; set; }
        public long IOTypeID { get; set; }
        public string Valu { get; set; }
        public System.DateTime TimeStamp { get; set; }
        public Nullable<System.DateTime> ExecTimeStamp { get; set; }
    
        public virtual Endpoint Endpoint { get; set; }
        public virtual IOType IOType { get; set; }
    }
}
