//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DynThings.DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class Endpoint
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Endpoint()
        {
            this.Alerts = new HashSet<Alert>();
            this.EndPointCommands = new HashSet<EndPointCommand>();
            this.EndPointIOs = new HashSet<EndPointIO>();
            this.LinkEndpointsLocations = new HashSet<LinkEndpointsLocation>();
        }
    
        public long ID { get; set; }
        public System.Guid GUID { get; set; }
        public System.Guid KeyPass { get; set; }
        public string PinCode { get; set; }
        public string Title { get; set; }
        public Nullable<long> DeviceID { get; set; }
        public long TypeID { get; set; }
        public long ColorID { get; set; }
        public long IconID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Alert> Alerts { get; set; }
        public virtual CssColor CssColor { get; set; }
        public virtual CssIcon CssIcon { get; set; }
        public virtual Device Device { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EndPointCommand> EndPointCommands { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EndPointIO> EndPointIOs { get; set; }
        public virtual EndPointType EndPointType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LinkEndpointsLocation> LinkEndpointsLocations { get; set; }
    }
}
