//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DynThings.DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class Notification
    {
        public long ID { get; set; }
        public string UserID { get; set; }
        public string Title { get; set; }
        public string Text { get; set; }
        public bool IsNew { get; set; }
        public System.DateTime TimeStamp { get; set; }
    }
}
